### ISSUE TITLE
Please update protos for v11.1

### ISSUE THREAD

**Issue by evil-shrike** [Opteo/google-ads-node#102]
Hi,
please regenerate proto for recently published v11.1. Lots of fields were added.

https://developers.google.com/google-ads/api/docs/release-notes#v11_1

**Comment by evil-shrike** [comment]
I tried running `make protos`, it builds a package but it doesn't contain a field added in v11.1, I looked at `AssetGroup.ad_strength`.
Though in https://github.com/googleapis/googleapis.git it does exists - see https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v11/resources/asset_group.proto#L90

**Comment by evil-shrike** [comment]
Hello, anyone?
Please take a look at the PR and update the lib for API v11.1 . The lib is lagging behind all other API clients.

**Comment by kritzware** [comment]
This library has now been upgraded to support v11.1 👌

**Comment by rosslavery** [comment]
Thank you @kritzware 🙏
