### ISSUE TITLE
Upgrade Google Ads to v15

### ISSUE THREAD

**Issue by PillowPillow** [Opteo/google-ads-node#117]
v15 was released on 2023-10-18, are you planning to update the library soon ?
Thanks for your lib btw !

https://developers.google.com/google-ads/api/docs/release-notes#v15

best regards,
Nicolas

**Comment by Larsfriishansen** [comment]
I would also like an update to v15 please

**Comment by markhorsman** [comment]
Are there any updates on this issue?

**Comment by marcosc90** [comment]
Are there any plans to update to v15?
