### ISSUE TITLE
Add examples directory

### ISSUE THREAD

**Issue by kritzware** [Opteo/google-ads-node#2]
### I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project

### Summary
We should add a variety of detailed examples

### Other information
Base examples on the official client libraries, e.g. [google-ads-python](https://github.com/googleads/google-ads-python)

**Comment by marcelinhov2** [comment]
I'm trying to use listAccessibleCustomers without success. Does anybody already used it?

Thanks

**Comment by marcelinhov2** [comment]
It's inside CustomerService

**Comment by kritzware** [comment]
Hi @marcelinhov2, the following code example works for me (using the latest version of this library):

```javascript
import { GoogleAdsClient, ListAccessibleCustomersRequest } from 'google-ads-node'

const client = new GoogleAdsClient({
    client_id: GADS_CLIENT_ID,
    client_secret: GADS_CLIENT_SECRET,
    developer_token: GADS_DEVELOPER_TOKEN,
    login_customer_id: GADS_LOGIN_CUSTOMER_ID_WITH_METRICS,
    refresh_token: GADS_REFRESH_TOKEN_WITH_METRICS,
})

const service = client.getService('CustomerService')

const request = new ListAccessibleCustomersRequest()

// Make sure you're inside an "async" function
const customers = await service.listAccessibleCustomers(request)
console.log(customers)
```

All the details of which request type and call to use, can be found [here in the Google Ads API documentation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#google.ads.googleads.v1.services.CustomerService) 👍

**Comment by marcelinhov2** [comment]
It don't list the things that I was looking for. I'm trying to replicate a flow that I saw at Word Stream website. I did the login with my mcc account and get a list of all the accounts that was under it.

![image](https://user-images.githubusercontent.com/232648/60369083-e8d08780-99c8-11e9-97ab-8a2e0f13e0eb.png)

![image](https://user-images.githubusercontent.com/232648/60369106-f980fd80-99c8-11e9-94cd-36dea053d48d.png)
![image](https://user-images.githubusercontent.com/232648/60369117-ff76de80-99c8-11e9-9c90-fdcf2fa840f0.png)

**Comment by marcelinhov2** [comment]
Do you have any idea where I can find something related to it?

Thanks 🙏

**Comment by marcelinhov2** [comment]
The code that you send, just return my main mcc account =/

**Comment by xpirt** [comment]
> Hi @marcelinhov2, the following code example works for me (using the latest version of this library):
> 
> ```js
> import { GoogleAdsClient, ListAccessibleCustomersRequest } from 'google-ads-node'
> 
> const client = new GoogleAdsClient({
>     client_id: GADS_CLIENT_ID,
>     client_secret: GADS_CLIENT_SECRET,
>     developer_token: GADS_DEVELOPER_TOKEN,
>     login_customer_id: GADS_LOGIN_CUSTOMER_ID_WITH_METRICS,
>     refresh_token: GADS_REFRESH_TOKEN_WITH_METRICS,
> })
> 
> const service = client.getService('CustomerService')
> 
> const request = new ListAccessibleCustomersRequest()
> 
> // Make sure you're inside an "async" function
> const customers = await service.listAccessibleCustomers(request)
> console.log(customers)
> ```
> 
> All the details of which request type and call to use, can be found [here in the Google Ads API documentation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.services#google.ads.googleads.v1.services.CustomerService) 👍

does it work for you on latest version (google api v3)?
