### ISSUE TITLE
Compiling protos on change of googleapis submodule version

### ISSUE THREAD

**Issue by orestisrodriguez** [Opteo/google-ads-node#28]
### I'm submitting a ...
  - [ ] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [X] question about how to use this project

### Summary
I want to use the latest version of google's definitions. I checked out an updated commit on the submodule and then tried to compile (`make protos`), without success. Any clarification on the procedure to compile the protos from the submodule to the google-ads-node package would be appreciated. Thanks :)

**Comment by kritzware** [comment]
Proto compilation should now be possible for anyone with Docker installed on their machine! See here for more information: https://github.com/Opteo/google-ads-node#protocol-buffers

I'm going to close this issue, feel free to re-open if you have any further questions.
