### ISSUE TITLE
Migration from grpc to grpc-js

### ISSUE THREAD

**Issue by xpirt** [Opteo/google-ads-node#37]
### I'm submitting a ...
  - [ ] bug report
  - [ ] feature request
  - [x] question about the decisions made in the repository
  - [ ] question about how to use this project

### Question
Hi there,
did you consider moving from `grpc` to `grpc-js` dependency? I think it is quite stable now to be used instead of the native dependency.

**Comment by avermeil** [comment]
Hi there!

What would be the advantages of using `grpc-js` rather than `grpc`?

**Comment by xpirt** [comment]
It seems `grpc@grpc-js` is now recommended instead of the native dependency by grpc authors. Mostly because of many compatibility issues on various platforms Node-based such as Electron.

For example, according to https://github.com/grpc/grpc-node/issues/778 the native dependency has still some issues when run on non context-aware environments (because of `nan` dependency): https://github.com/grpc/grpc-node/issues/778#issuecomment-546429941.

As `@grpc-js` is more mature, many developers (including Google: https://github.com/firebase/firebase-js-sdk/issues/1783) are migrating/or already have migrated for the same issues.

**Comment by xpirt** [comment]
@avermeil As for the `grpc.max_send_message_length` and `grpc.max_receive_message_length` channel arguments, they have already been approved (https://github.com/grpc/grpc-node/pull/1346) and being merged as we speak.
They are coming in `0.8.0` version.

**Comment by kritzware** [comment]
This is something we'll be working on soon 👍

**Comment by kritzware** [comment]
This is resolved now, and we recommend using [google-ads-api](https://github.com/opteo/google-ads-api) which now supports Google Ads API v6.1.
