### ISSUE TITLE
campaigns of "discovery" type cannot be fetched

### ISSUE THREAD

**Issue by grinsteindavid** [Opteo/google-ads-node#48]
### I'm submitting a ...

-   [x] bug report
-   [x] feature request

### Summary

When using:

`let result = await customer.campaigns.list()`

It fetches all the remote campaigns but not the campaigns of discovery type https://support.google.com/google-ads/answer/9176876?hl=en

**Comment by jeanlescure** [comment]
We are having the same problem, is this possible at all with the current version?

**Comment by kritzware** [comment]
[See here for more information](https://github.com/Opteo/google-ads-api/issues/146), but unfortunately Google haven't made campaigns of type Discovery available through the API.
