### ISSUE TITLE
NPM webpage is broken

### ISSUE THREAD

**Issue by episage** [Opteo/google-ads-node#5]
### I'm submitting a ...
  - [X] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project

### Summary
![image](https://user-images.githubusercontent.com/2196095/53871208-164d8b80-3ffc-11e9-9120-6ab4f009e150.png)

### Other information
Tested just now and a couple days ago. It is downloadable via npm tho.

**Comment by avermeil** [comment]
Are you using an ad-blocker? Those don't play nice with NPM and Github for our library name which has the word "ads" in it...

**Comment by episage** [comment]
You are right... uBlock... I disabled it and it went through.
Thanks
