### ISSUE TITLE
Is there an option to Upload Offline Conversion

### ISSUE THREAD

**Issue by mishaniyoni** [Opteo/google-ads-node#51]
### I'm submitting a ...
  - [ ] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [x] question about how to use this project
  

### Summary
Google docs:
https://developers.google.com/google-ads/api/docs/samples/upload-offline-conversion#java

I need to be able to report offline conversion to Google Ad account. I couldn't find this method in "conversion_upload_service_pb.d.ts", Is there a way to do it?, or is it just a regular UploadClickConversionsRequest?
Much appreciated ahead of time!

**Comment by kritzware** [comment]
Are you using google-ads-api or google-ads-node? 

With google-ads-api we have some examples in our docs here: https://opteo.com/dev/google-ads-api/#conversionupload

**Comment by kritzware** [comment]
This is possible in the newest version of [google-ads-api](https://github.com/opteo/google-ads-api).
