### ISSUE TITLE
CriterionCategoryAvailability.locale should be .locale_list

### ISSUE THREAD

**Issue by markoffk** [Opteo/google-ads-node#55]
Hello.
Here is current typing definition:

export interface CriterionCategoryAvailability {
    channel?: CriterionCategoryChannelAvailability;
    **locale**?: CriterionCategoryLocaleAvailability[];
}

Should be:

export interface CriterionCategoryAvailability {
    channel?: CriterionCategoryChannelAvailability;
    **locale_list**?: CriterionCategoryLocaleAvailability[];
}

BR, Vlad

**Comment by kritzware** [comment]
This is now resolved and we recommend upgrading to the latest [google-ads-api](https://github.com/opteo/google-ads-api) version (Google Ads API v6.1)
