### ISSUE TITLE
Label missing fields in resources.ts

### ISSUE THREAD

**Issue by akhtariev** [Opteo/google-ads-node#64]
### I'm submitting a ...
  - [X] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project
  
### Summary
This is a follow-up to [this issue](https://github.com/Opteo/google-ads-node/issues/62). After investigating, I found out that Label's interface in `resources.ts` is missing fields specified in the [API](https://opteo.com/dev/google-ads-api/#label). As a result, the fields are also missing from the compiled version of the resources. I tried adding the fields on my fork [here](https://github.com/Opteo/google-ads-node/compare/master...akhtariev:label-no-fields). 

However, I could not compile the resources and investigate further because I don't have the Docker permissions. I was wondering if someone could please provide an ETA on this issue.  Also, is there an option of relaxing the permissions so that I could investigate further myself and open up a PR?

This is blocking me significantly. Any info would be very much appreciated. I can provide more details if needed.
Thanks a lot!

**Comment by WillCooter** [comment]
This is now resolved and we recommend upgrading to the latest [google-ads-api](https://github.com/opteo/google-ads-api) version (Google Ads API v6.1)
