### ISSUE TITLE
How to get the login_customer_id of a client account programatically? 

### ISSUE THREAD

**Issue by ikkhannn** [Opteo/google-ads-node#68]
### I'm submitting a ...
  - [ ] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [x] question about how to use this project
  

### Summary

Is there any way to get the manager id (login_customer_id) of a client account programatically?

**Comment by WillCooter** [comment]
We're not sure on this one, best to direct your answer to the [Google Ads api support team](https://groups.google.com/g/adwords-api?pli=1).
