### ISSUE TITLE
Receiving RESOURCE_EXHAUSTED: received trailing metadata size exceeds limit

### ISSUE THREAD

**Issue by rosslavery** [Opteo/google-ads-node#70]
### I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [ ] question about how to use this project
  

### Summary
Large sets of mutations cause a `RESOURCE_EXHAUSTED` error with the following details:

```
"failure":{
      "code": 8,
      "details": "received trailing metadata size exceeds limit"
   }
```

### Other information
This seems to be a problem with gRPC response size being capped as part of this library. When a response size is too large, a generic `received trailing metadata size exceeds limit` error is sent back, which obfuscates the actual cause of the error.

Spoke to Google support about this (provided them a request id) and they said the following (note I linked them to a similar issue from their officially-supported Python API Wrapper):

> [The Python issue you referenced](https://github.com/googleads/google-ads-python/issues/38) has since been resolved, as we increased the grpc metadata size in September. However, since the error message from nodejs appears to be the same grpc error, there is a good chance that either the metadata size increase was not large enough for this particular response, or that the response size limit that's set in the nodejs library here is actually separate from the metadata size limit. I will follow up with the team about this issue to see what we can do, and will respond here as soon as I have updates for you.

and

> I have investigated more deeply into the issue and confirmed that the longest response metadata for your requests (~42kb) is still shorter than what we have bumped the metadata size limit to (64kb). Since the equivalent issue has been resolved for Google-owned client libraries, even for response metadata longer that what is causing problems for you, the most likely case is that this error is manifesting due an Opteo-specific gRPC setup. Our recommendation is to file a Github Issue with the NodeJS client library open sourced by Opteo to have them look into the issue, and hopefully then you will have a resolution soon.

[I see that you increase the message here](https://github.com/Opteo/google-ads-node/blob/b31c6225986729fc305ca1d2226e22b9bd9ff1af/src/lib/client.ts#L102) but according to the email from Google above, my response payload for the problematic request was only ~42kb which is obviously well under the 1gb being set in the gRPC client for this library.

This has been a frequent issue for us in specific parts of our application, and would love to help get it fixed!

**Comment by WillCooter** [comment]
We recommend trying the latest [google-ads-api](https://github.com/opteo/google-ads-api) version (Google Ads API v6.1). Let us know if you have any further issues with this.
