### ISSUE TITLE
Problem with authorization

### ISSUE THREAD

**Issue by Bukareszt** [Opteo/google-ads-node#94]
**Hey guys!**
Currently i am started to working with this library, because I needs some things from google API v10, and library google-ads-api currently supports only v9.

**And my question is:**
How to authorize with my Google Ads Account?
In the case of working with google-ads-api, everything works, so it is not the fault of bad data.

My current code looks like this:

```javascript
import { CustomerServiceClient } from "google-ads-node";
 async function makeCall() {
   const client = new CustomerServiceClient({
     clientOptions: {
       clientId: "myClientId",
       clientSecret: "myClientSecret",
       refreshToken: "myRefreshToken"
     },
   });
   const response = await client.listAccessibleCustomers();
   return response;
}
```

I receive: Error: 7 PERMISSION_DENIED: Request had insufficient authentication scopes.
I am more then sure that is because I didn't pass developer token.

And question is: how to pass it/and and is the rest okay (I mean clientOptions)?

**Comment by kritzware** [comment]
We've just released v10 support for google-ads-api so you should be able to continue using that library now!
